### ISSUE TITLE
Are you accepting pull requests?

### ISSUE THREAD

**Issue by gyrrhe** [danielcharrua/secure-encrypted-form#3]
Hi!

I think your plugin is good and I'd like to improve it, and in particular fix the issues I raised some months ago, #1 and #2. If I were to submit pull requests for these issues or other features, would you have time to review the pull requests and accept them if you think they're good?

If this isn't possible, I will consider forking the plugin, which is also of course a solution.

Thanks!

**Comment by danielcharrua** [comment]
Hey @gyrrhe PR's are welcomed!

So, if you have time and energy please send your modifications, I'll be happy to approve them 💪
